#!/usr/bin/env perl
use strict;
use Getopt::Std;
use Encode;

# ----------------------------------------------------------------------
# All fields in UnicodeData.txt, in the order they appear in each line.
my $all_fnames   = "codept,name,cat,comb,bidi,decomp,decval,digval,numval,mirror,oldname,cmt,ucmap,lcmap,titmap";

my $short_fnames = "char,codept,utf8,name";
my $med_fnames   = "char,codept,utf8,cat,ucmap,lcmap,name";
my $long_fnames  = "char,codept,utf8,width,cat,bidi,comb,ucmap,lcmap,titmap,decomp,decval,digval,numval,mirror,name,oldname,cmt";

my $usage = <<_EOF_;
usage: unicode [options] [selector]...
       Prints all glyphs whose name matches all selectors.
       Each selector is a comma-separated list of patterns, and
       a glyph matches the selector if it matches any of the patterns.
       A pattern is either a Unicode code point in the form U+xxxx,
       or a range in the form U+xxxx-U+yyyy, or a regular expression
       to match the name.
   Options:
       -f <file>   Name of UnicodeData.txt file.
       -h          Print header before one-line output.
       -l          Long output.
       -L          Complete output.
       -m          Multi-line output.
       -p <fields> Print only listed fields (from $all_fnames).
       -w <file>   Name of EastAsianWidth.txt file.
_EOF_

# ----------------------------------------------------------------------
my %field_width = (
    'char'    => 2,
    'codept'  => 5,
    'name'    => 50,
    'oldname' => 50,
    'bidi'    => 3,
    'cat'     => 2,
    'comb'    => 5,
    'decomp'  => 24,
    'decval'  => 1,
    'digval'  => 1,
    'mirror'  => 1,
    'numval'  => 5,
    'ucmap'   => 5,
    'lcmap'   => 5,
    'titmap'  => 5,
    'utf8'    => 11,
    'width'   => 2,
);
my %field_title = (
    'char'    => "ch",
    'codept'  => "code",
    'name'    => "name",
    'oldname' => "old name",
    'bidi'    => "bi",
    'cat'     => "ct",
    'comb'    => "+",
    'decomp'  => "decomp",
    'decval'  => "d",
    'digval'  => "g",
    'mirror'  => "m",
    'numval'  => "num",
    'ucmap'   => "uc",
    'lcmap'   => "lc",
    'titmap'  => "title",
    'utf8'    => "utf-8",
    'width'   => "w",
);

my %nonprint = (
    "Mc" => 1, # Mark, Spacing Combining
    "Me" => 1, # Mark, Enclosing
    "Mn" => 1, # Mark, Nonspacing
    "Cc" => 1, # Other, Control
    "Cf" => 1, # Other, Format
    "Co" => 1, # Other, Private Use
    "Cs" => 1, # Other, Surrogate
    "Xx" => 1, # (omit, internal use)
    "Zl" => 1, # Separator, Line
    "Zp" => 1, # Separator, Paragraph
);

my %wide_prop = ( 'F' => 1, 'W' => 1 ); # East Asian Fullwidth or Wide
my %bad_bidi = ( 'R' => 1, 'AL' => 1, 'AN' => 1 ); # Right-to-left, Arabic, or Arabic number

my @force_omit = (
    [0xad,    0xad],    # SOFT HYPHEN
    [0x200d,  0x200d],  # ZERO WIDTH JOINER
    [0x1f3fb, 0x1f3ff], # EMOJI MODIFIER FITZPATRICK TYPE-[1-6]
    [0x1f9b0, 0x1f9b3], # EMOJI COMPONENT [RED,CURLY,BALD,WHITE] HAIR
    [0xfe00,  0xfe0f],  # VARIATION SELECTOR-[1-16]
    [0xe0100, 0xe01ef], # VARIATION SELECTOR-[17-256]
);
my $force_omit;

my @force_compose = (
    [0x1160, 0x11ff],
    [0xd7b0, 0xd7c6],
    [0xd7cb, 0xd7fb]
);
my $force_compose;

# ----------------------------------------------------------------------
exit (main() ? 0 : 1);

sub main {
    my %opt;
    die $usage if not getopts("f:hlLmp:w:", \%opt);
    my $ufilename = ($opt{f} or progdir()."UnicodeData.txt");
    my $wfilename = ($opt{w} or progdir()."EastAsianWidth.txt");
    my $prt = $opt{p} ? $opt{p} :
        $opt{L} ? $long_fnames : $opt{l} ? $med_fnames : $short_fnames;

    $force_compose = mktable(\@force_compose);
    $force_omit = mktable(\@force_omit);

    my $ufile = read_unicode_file($ufilename);
    my $wfile = read_width_file($wfilename);
    return 0 if not $ufile;
    print_header($prt) if ($opt{h} and not $opt{m});
    return search_unicode_file($ufile, $wfile, $prt, (not $opt{m}), @ARGV);
}

# ----------------------------------------------------------------------
sub mktable {
    my ($ranges) = @_;
    my %table;
    foreach my $comp (@$ranges) {
        my ($lo,$hi) = @$comp;
        for (my $ch = $lo; $ch <= $hi; ++$ch) {
            $table{$ch} = 1;
        }
    }
    return \%table;
}

# ----------------------------------------------------------------------
sub read_unicode_file {
    my ($file) = @_;
    my $fd;
    if (not open($fd, '<', $file)) {
        print "cannot open $file: $!\n";
        return undef;
    }
    my @glyphs;
    while (<$fd>) {
        chomp;
        my @fields = split /;/;
        my %glyph;
        my $codept = -1;
        my $index = 0;
        foreach my $fname (split /,/, $all_fnames) {
            my $field = $fields[$index++];
            if ($fname eq "codept") {
                $codept = hex($field);
            } elsif ($fname eq "cat") {
                $field = "Mn" if $force_compose->{$codept};
                $field = "Xx" if $force_omit->{$codept};
            }
            $glyph{$fname} = $field;
        }
        push @glyphs, \%glyph;
    }
    close $fd;
    my %ufile = ( 'glyphs' => \@glyphs );
    return \%ufile;
}

# ----------------------------------------------------------------------
sub read_width_file {
    my ($file) = @_;
    my $fd;
    if (not open($fd, '<', $file)) {
        print "cannot open $file: $!\n";
        return undef;
    }
    my %widths;
    while (<$fd>) {
        chomp;
        if (/^\s*([0-9A-Fa-f]+)(\.\.([0-9A-Fa-f]+))?\s*;\s*(\w+)/) {
            my $lo = hex($1);
            my $hi = defined($3) ? hex($3) : $lo;
            my $prop = $4;
            if ($wide_prop{$prop}) {
                for (my $ch = $lo; $ch <= $hi; ++$ch) {
                    $widths{$ch} = 2;
                }
            }
        }
    }
    close $fd;
    return \%widths;
}

# ----------------------------------------------------------------------
sub search_unicode_file {
    my $ufile = shift @_;
    my $wfile = shift @_;
    my $prt = shift @_;
    my $oneline = shift @_;
    foreach my $glyph (@{$ufile->{glyphs}}) {
        if (glyph_match($glyph, @_)) {
            print_glyph($glyph, $wfile, $prt, $oneline);
        }
    }
}

# ----------------------------------------------------------------------
sub glyph_match {
    my $glyph = shift @_;
    foreach my $pat (@_) {
        return 0 if not glyph_match2($glyph, $pat);
    }
    return 1;
}
sub glyph_match2 {
    my ($glyph, $pat) = @_;
    foreach my $subpat (split /,/, $pat) {
        return 1 if glyph_match3($glyph, $subpat);
    }
    return 0;
}
sub glyph_match3 {
    my ($glyph, $pat) = @_;
    my $codept = hex($glyph->{codept});
    if ($pat =~ /^[uU]\+([0-9a-fA-F]+)-[uU]\+([0-9a-fA-F]+)/) {
        return ($codept >= hex($1) and $codept <= hex($2));
    }
    if ($pat =~ /^[uU]\+([0-9a-fA-F]+)/) {
        return (hex($1) == $codept);
    }
    return ($glyph->{name} =~ /$pat/i);
}

# ----------------------------------------------------------------------
sub print_glyph {
    my ($glyph, $wfile, $prt, $oneline) = @_;
    my $utf8 = glyph_utf8($glyph);
    my $cw = glyph_width($glyph, $wfile);
    my @fnames = split /,/, $prt;
    for (my $p = 0; $p < @fnames; ++$p) {
        my $fname = $fnames[$p];
        my $val = ($fname eq "char") ? $utf8 :
                  ($fname eq "utf8") ? bytes($utf8, length($utf8)) :
                  ($fname eq "width") ? $cw :
                  $glyph->{$fname};
        if ($oneline) {
            my $fwidth = $field_width{$fname};
            my $ps = $val;
            my $pw = ($fname eq "char") ? $cw : length($ps);
            if ($pw > $fwidth and $p+1 < @fnames) {
                $ps = substr($ps, 0, $fwidth-1) . "…";
                $pw = $fwidth; ##length($ps);
            }
            printf("%s", $ps) if $pw > 0;
            printf("%-*s", $fwidth+1-$pw, '') if $pw < $fwidth+1;
        } elsif ($fname eq "char" and $cw == 0) {
            ;
        } else {
            printf "%-8s %s\n", $fname, $val if length($val) > 0;
        }
    }
    printf "\n";
}

# ----------------------------------------------------------------------
sub print_header {
    my ($prt) = @_;
    foreach my $fname (split /,/, $prt) {
        my $width = $field_width{$fname};
        printf "%-*s", $width+1, uc $field_title{$fname} if $width;
    }
    printf "\n";
}

# ----------------------------------------------------------------------
sub glyph_utf8 {
    my ($glyph) = @_;
    return encode("UTF-8", chr(hex($glyph->{codept})));
}

# ----------------------------------------------------------------------
sub bytes {
    my ($s, $n) = @_;
    my $r = '';
    for (my $i = 0; $i < $n; ++$i) {
        my $b = $i < length($s) ? sprintf("%02x", ord(substr($s,$i,1))) : "  ";
        $r .= $b;
        $r .= " " if $i+1 < $n;
    }
    return $r;
}

# ----------------------------------------------------------------------
sub progdir {
    my ($dir) = $0 =~ m|^(.*/)[^/]*$|;
    $dir = "./" if length($dir) == 0;
    return $dir;
}

# ----------------------------------------------------------------------
sub glyph_width {
    my ($glyph, $wfile) = @_;
    return 0 if $nonprint{$glyph->{cat}};
    return 0 if $bad_bidi{$glyph->{bidi}};
    my $w = $$wfile{hex $glyph->{codept}};
    return defined($w) ? $w : 1;
}
